#The time in ticks in which a player can still be rescued from death. Set to 0 to disable the timer.
#Range: > -2147483648
ticksUntilDeath = 6000
#If true, the timer until death continues even if the player logs out.
continueTimerWhileOffline = false
#The time in ticks it takes to rescue a player.
#Range: > -2147483648
rescueActionTicks = 1
#The amount of health to respawn with when a player was rescued, out of 20.
#Range: > -2147483648
rescueRespawnHealth = 20
#The food level to respawn with when a player was rescued, out of 20.
#Range: > -2147483648
rescueRespawnFoodLevel = 20
#Effects applied to a player when rescued, in the format "effect|duration|amplifier"
rescueRespawnEffects = ["minecraft:regeneration|30|9", "minecraft:resistance|10|3"]
#The distance at which a player can rescue another.
#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
rescueDistance = 5.0
#If true, knocked out players will glow, making them visible through blocks.
glowOnKnockout = true
#If true, knocked out players are still able to punch nearby enemies.
allowUnarmedMelee = true
#If true, knocked out players are still able to fire bows.
allowBows = true
#If true, knocked out players are still able to fire pistols from Mr Crayfish's Gun Mod.
allowPistols = true

